spring:

  #devtools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # jpa
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# server
server:
  port: 8080